Update hivesmodals.html
LBRYFoundation/lbryorg pull request #19
Opened 2020-11-18 06:55 UTC by ElectronEsq

lbry.science just redirects to an unrelated website. Not sure if LBRY Science is even a thing or not, so didn't remove it completely.
LBRY Records website no longer exists.

2020-11-18 12:31 UTC, Coolguy3289 requested changes

2020-11-18 12:31 UTC, Coolguy3289 commented on _includes/hivesmodals.html
> -
To my knowledge, lbry.science and BOINC are one and the same. JRingo runs this hive and it is still active last I checked. Please revert this change and restore the site link.

2020-11-18 12:31 UTC, Coolguy3289 commented on _includes/hivesmodals.html
> -
LGTM

2020-11-19 10:48 UTC, ElectronEsq commented on _includes/hivesmodals.html
> -
The link isn't anything to do with LBRY. It's just a Boinc site. Furthermore the site doesn't have an SSL and is using dummy text. It's best to remove this, then if the site becomes a fully working LBRY related site at a later date, add it back then. As it stands it has no purpose on the site and reflects badly on the brand.

![image](https://user-images.githubusercontent.com/29914179/99656173-4f67b100-2aa8-11eb-916d-a4e13a27953c.png)

![image](https://user-images.githubusercontent.com/29914179/99656035-26dfb700-2aa8-11eb-9f31-db8969361d7b.png)

2020-11-21 16:10 UTC, Coolguy3289 commented on _includes/hivesmodals.html
> -
Just confirmed, that site is correct for lbry.science

2020-11-21 16:13 UTC, jring-o commented
Go ahead and remove it. It's a sandbox for the time being.

2020-11-21 16:14 UTC, Coolguy3289 commented
Just resolve the conflicts and I'll get this merged

2020-12-03 05:15 UTC, Eniamza commented
@Coolguy3289 Ready to merge I guess

2020-12-03 05:27 UTC, Coolguy3289 commented
No, because of the upstream merge. The !role command documentation has been added again, as well as the website that Jon approved removing.

2020-12-03 12:47 UTC, Eniamza commented
Ah,  I probably reverted messed up something.
Checking...

2020-12-03 16:41 UTC, Eniamza commented
Updated it manually

2020-12-06 07:34 UTC, closed without merging